# This workflow will install Python dependencies, run tests using uv.
# It can be tested locally using https://github.com/nektos/act with the command `act push --container-architecture linux/amd64 -j test`

name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install the project
        run: uv sync --all-extras --all-groups

      - name: Run tests
        run: uv run pytest

      - name: Run lint
        run: uv run ruff check

      - name: Run formatter check
        run: uv run ruff format --check

      - name: Run doctest
        # Check that code examples in docs execute as expected, and treat warnings as errors
        run: cd docs/source && uv run make doctest SPHINXOPTS="-W --keep-going -n"
